# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006f0c7c5507e8feb4d2816639120edf43ddaf025824ab99d13f7569d071d8866884e1005485ca03be009e0d4be5176fe7e965f948a68e88d1e1c1d9c2af8981

test:
  secret_key_base: 9f2dedd0842b6bef3879de958ed70b63a7407e5de8c3c33a7892f27529f7cf0fad21d4d899837be0f121e5237b61b20b80ef8ed4940222e00964767f483b20a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
